user  www-data;
# Set number of worker processes automatically based on number of CPU cores.
worker_processes  auto;

# Configures default error logger.
error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;


events {
	# The maximum number of simultaneous connections that can be opened by
	# a worker process.
    worker_connections  1024;
}


http {
	# Includes mapping of file name extensions to MIME types of responses
	# and defines the default type.
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

	# Specifies the main log format.
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

	# Sets the path, format, and configuration for a buffered log write.
    access_log  /var/log/nginx/access.log  main;

	# Sendfile copies data between one FD and other from within the kernel,
	# which is more efficient than read() + write(). Default is off.
    sendfile        on;

    keepalive_timeout  65;

    include /etc/nginx/conf.d/*.conf;

    server {
        listen 8080; 
        server_name localhost ${NGINX_HOST};

        listen 443 ssl;
        listen [::]:443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
        
        root /var/www/html/galambey.42.fr;
        index  index.php index.html index.htm;

        location / {
            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            fastcgi_split_path_info  ^(.+\.php)(/.+)$;
            fastcgi_param SCRIPT_FILENAME $request_filename;
			fastcgi_pass wordpress:9000;
			include fastcgi_params;
        }
    }
}
